server:
  http_listen_port: 3100

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
    zipkin:
      endpoint: 0.0.0.0:9411

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  trace_idle_period: 10s
  flush_check_period: 5s
  max_block_duration: 5m

memberlist:
  join_members:
    - tempo1:7946

compactor:
  compaction:
    compaction_window: 1h
    max_compaction_objects: 1000000
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000