auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    s3:
      endpoint: http://minio:9000
      bucketnames: loki
      access_key_id: admin
      secret_access_key: password123
      s3forcepathstyle: true
      region: us-east-1
      insecure: true
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2025-08-12
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    s3: s3
    s3forcepathstyle: true
    bucketnames: loki-data
    endpoint: http://minio:9000
    access_key_id: admin
    secret_access_key: password123
    insecure: true
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 24h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: inmemory

limits_config:
  #  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  # Configure ingestion limits
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 10MB
  # Chunk configuration for minute-level separation
  max_streams_per_user: 10000
  max_line_size: 256000
  split_queries_by_interval: 15m

# Chunk store configuration
chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 100

ruler:
  storage:
    s3:
      bucketnames: loki-ruler
#  rule_path: /loki/rules
#  ring:
#    kvstore:
#      store: inmemory
#  enable_api: true

# Analytics and usage reporting
analytics:
  reporting_enabled: false

# Memberlist configuration
memberlist:
  node_name: loki-1
  randomize_node_name: false